# Run Test
name: ci

on:
  - push
  - pull_request

jobs:
  compliance-ubuntu:
    name: compliance
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

